universal9611: Move to soong_config_set_bool for cbd
error: hardware/samsung_slsi-linaro/exynos/cpboot_v3/Android.bp:12:11: module cbd variant android_vendor_arm64_armv8-a_cortex-a53: cflags: Expected all branches of a select on condition soong_config_variable(cbd, use_legacy_sipc_ioctl) to have type string, found bool